module.exports = {
	pluginName: 'nanato-seo',
	mainFile: 'nanato-seo.php',
	buildDir: 'dist',
	zipName: '{{name}}-{{version}}.zip',
	excludePatterns: [
		'.*',
		'.docs/',
		'.claude/',
		'.git/',
		'.github/',
		'.scripts/',
		'node_modules/',
		'vendor/',
		'composer.json',
		'composer.lock',
		'package.json',
		'package-lock.json',
		'dist/',
		'src/',
		'*.md',
		'*.zip',
		'phpcs.xml.dist',
		'*.config.js',
	],
	config: {
		includeGitOps: true,
		tagPrefix: 'v',
		branch: 'main',
	},
	hooks: {
		preRelease: [],
		postRelease: [],
		preBuild: [],
		postBuild: [],
	},
};
